### ISSUE TITLE
Nothing happens when I click the Login button

### ISSUE THREAD

**Issue by fernand0dias** [JohnRSim/0xTr.ee#1]
Doing good guys? I found the project interesting, I can't connect my Metamask wallet either on the site or locally

**Comment by JohnRSim** [comment]
Hi - this was a quick Hackathon concept. The team are not maintaining or keeping the project going unfortunately.

Many thanks for your interest.

**Comment by fernand0dias** [comment]
No problem, this repo is helping me creating the initial Sveltekit + Moralis setup
